version: "3"ßß
services:

  zeebe:
    image: camunda/zeebe:8.4.0
    container_name: zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
    environment:
      - ZEEBE_BROKER_NETWORK_HOST=0.0.0.0
      - ZEEBE_BROKER_GATEWAY_NETWORK_HOST=0.0.0.0